application: home-journal
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.(html))
  static_files: static/\1
  upload: static/(.*\.(html))

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
